server:
  port: 9002
spring:
  application:
    name: bbs-user-service
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:127.0.0.1:8848}
      username: nacos
      password: 123456
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/bbs_user_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456}
  sql:
    init:
      mode: always
      continue-on-error: true
      schema-locations: classpath:schema.sql
  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:123456}
  cache:
    type: redis
    redis:
      time-to-live: 600000
      cache-null-values: false
mybatis:
  type-aliases-package: com.li.bbs.user.domain
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
management:
  endpoints:
    web:
      exposure:
        include: health,info

